meta_product_name: "Huchi"
meta_title: "Huchi - Disparition"
meta_description: "Retrouvons nos disparus"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
